### ISSUE TITLE
View Products by Category

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#10]
### User Story: [View Products by Category](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C3) 

As a **User** I want to **view product by category** so that **I can view products in alphabetical order**

***

### Acceptance Criteria:
- Customer can view all products by by category in alphabetical order

***

### Tasks: 
- [ ] Create all products page
- [ ] Sort products in alphabetical order
- [ ] Test price order function is working correctly
