### ISSUE TITLE
View Product Ratings

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#11]
### User Story: [View ratings for each product ](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C4) 

As a **User** I want to **view the ratings for each product** so that **I can decide if it is something worth buying**

***

### Acceptance Criteria:
- Ratings for products appear on small view of products on All Products page
- Ratings for products appear next to product image on individual product pages

***

### Tasks: 
- [ ] Create all products page
- [ ] Add product ratings to each product
- [ ] Set product rating to appear under image on All Products page
