### ISSUE TITLE
Add Own Rating For a Product

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#12]
### User Story: [Add my own rating for a product ](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C5) 

As a **User** I want to **be able to add my own rating for a product I purchased** 

***

### Acceptance Criteria:
- Registered users have the ability to add a rating for a product
- Site admin have the ability to vet the ratings to make sure they aren't spam 

***

### Tasks: 
- [ ] Create user sign up function 
- [ ] Create ratings form 
- [ ] Link ratings form to product pages
