### ISSUE TITLE
Add reviews from products

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#14]
### User Story: [Add reviews from products ](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C6) 

As a **User** I want to **add a review for a product I have purchased** so that **give feedback on products**

***

### Acceptance Criteria:
- Registered site users can leave reviews for products they have previously purchased
- Admin staff can vet the reviews to make sure they are from actual customers and not spam 

***

### Tasks: 
- [ ] Create comment box on products bag
- [ ] Make sure comment box only appears if the user is registered 
- [ ] Allow for admin staff to approve or reject reviews
