### ISSUE TITLE
View Shopping basket

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#16]
### User Story: [View shopping basket ](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C9) 

As a **User** I want to **view the products in my shopping basket**

***

### Acceptance Criteria:
- Users can add a product to their shopping basket from the product details page
- Users can select the quantity of products they would like to add

***

### Tasks: 
- [ ] Create the basket
- [ ] Link each product to the basket
- [ ] Add calculation logic so grand total can be calculated
