### ISSUE TITLE
Sign up for newsletter with an email address

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#28]
### User Story: [Sign up for newsletter with an email address ](https://docs.google.com/spreadsheets/d/1tVnHzRfP0hPory2GUCfKkiKpfxxGOuGtRkeizTLchqo/edit#gid=0&range=C21) 

As a **User** I want to **sign up for the websites newsletter** so that **I can be notified of any offers and new products**

***

### Acceptance Criteria:
- Users can sign up to a company newsletter
- Users will receive a confirmation email 

***

### Tasks: 
- [ ] Create sign up page
- [ ] Add sign up form 
- [ ] Connect to an email client
- [ ] Test
