### ISSUE TITLE
View Products by Price 

### ISSUE THREAD

**Issue by Martiless** [Martiless/Alices-Wonderland#9]
### User Story: View Products by Price 

As a **User** I want to **view product by price** so that **I can choose products in my price range**

***

### Acceptance Criteria:
- Customer can view all products by price in ascending order

***

### Tasks: 
- [ ] Create all products page
- [ ] Sort products in ascending order
- [ ] Test price order function is working correctly
